# Método por prueba y error para $\alpha$

Este método se emplea comunmente en aplicaciones de ML. En este caso se recomienda iniciar con valores pequeños de $\alpha$, por ejemplo 0.01, y se aumenta en caso de ser necesario. debemos ajustar nuestro parámetro $\alpha$ para asegurar que el algoritmo de descenso de gradiente converja en un tiempo razonable. La falta de convergencia o demasiado tiempo para obtener el valor mínimo implica que nuestro tamaño de paso es incorrecto. Con un tamño de paso incorrecto podemos encontral los siguentes problemas:

- Si $\alpha$ es muy pequeño el descenso puede ser muy lento.
- Si $\alpha$ es muy grande podríamos sobrepasar el punto de mínima.

Recordemos la expresión matemática que describe el descenso del gradiente:

$$
\hat{\theta}^{(k+1)} = \hat{\theta}^{(k)} - \alpha \nabla J(\hat{\theta}^{(k)}).
$$

Es importante notar que el descenso de gradiente con un tamaño de paso fijo $\alpha$ puede converger, ya que a medida que nos acercamos a un punto de mínima, el tamaño de paso decrece debido a que el gradiente $\nabla J(\hat{\theta}^{(k)})$ decrece en cada iteración.

**Ejemplo**

Para entender la dinámica de este algoritmo, considere la siguente matriz y vector

$$
A = X^T X = 
\begin{pmatrix}
10 & 0 \\
0 & 1
\end{pmatrix}, \quad b = X^T y
\begin{pmatrix}
1 \\
-1
\end{pmatrix}
$$

Con los cuales contruimos la función objetivo (paraboloide)

$$
J(\theta) = \frac{1}{2}\theta^T A\theta - b^T \theta  = \frac{1}{2}\theta^T X^T X\theta - X^T y \theta = 5 \theta_0^2 + \frac{1}{2} \theta_1^2 - \theta_0 + \theta_1
$$

Las siguentes celdas de código demuestran el proceso para obtener una aproximación a un punto de mínima usando el método de descenso del gradiente con $\alpha$ fijo ajustado mediante prueba y error.

In [1]:
# requirements
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import pandas as pd

plt.style.use('ggplot')
%matplotlib ipympl

In [2]:
def steepestDescent(A, b, theta, alpha, tol, M):
    """
    Steepest descent algorithm for fixed alpha.
    
    This algorithm takes as input A = X.T @ X and
    b = X.T @ y.
    
    This is not a practical implementation as it
    returns the recors of J and theta parameter to
    plot the way down to the minimum.
    
    Input parameters
    A: defined as X.T @ X
    b: defined as X.T @ y
    theta: initial approximation
    alpha: fixed learning rate
    tol: tolerance
    M: maximum number of iterations
    
    Output
    theta_rec: recorded parameters theta
    J_rec: recorded values of J at theta_rec
    """
    
    J = 0.5*theta.T @ A @ theta - b.T @ theta
    theta_rec = theta.T
    J_rec = J
    k = 0
    while k < M:
        rk = A @ theta - b # Gradient
        if np.linalg.norm(rk) < tol:
            print('The procedure was successful.')
            return theta_rec, J_rec
        
        k += 1
        theta = theta - alpha*rk
        J = 0.5*theta.T @ A @ theta - b.T @ theta
        theta_rec = np.vstack((theta_rec, theta.T)) # Store theta_k
        J_rec = np.vstack((J_rec, J)) # Store J(theta_k)
        
    print("Maximum number of iterations reached")
    return theta_rec, J_rec

Para probar el algoritmo usamos inicialmente $\alpha = 0.01$ con $\theta = (1, 1)^T$

In [3]:
A = np.array([[10, 0], [0, 1]])
b = np.array([[1], [-1]])

theta = np.array([[1], [1]])
tol = 0.01
M = 1000
alpha = 0.01

theta_rec, J_rec = steepestDescent(A, b, theta, alpha, tol, M)
data = np.hstack((theta_rec, J_rec))
pd.DataFrame(data, columns=["theta0", "theta1", "J(theta)"])

The procedure was successful.

      theta0    theta1  J(theta)
0    1.00000  1.000000  5.500000
1    0.91000  0.980000  4.690700
2    0.82900  0.960200  4.028397
3    0.75610  0.940598  3.485296
4    0.69049  0.921192  3.038882
..       ...       ...       ...
524  0.10000 -0.989675 -0.549947
525  0.10000 -0.989779 -0.549948
526  0.10000 -0.989881 -0.549949
527  0.10000 -0.989982 -0.549950
528  0.10000 -0.990082 -0.549951

[529 rows x 3 columns]

Como podemos observar este algoritmo requiere de 529 iteraciones para alcanzar una aproximación deseada del punto míninmo de $J(\theta)$. Una forma de observar la convergencia del algoritmo es mediante un gráfico de valores de $J(\theta)$ versus el numero de iteraciones como se muestra a continuación

In [4]:
fig = plt.figure(figsize=(8, 4))
ax = fig.add_subplot(1,1,1)
ax.plot(J_rec, '.')
ax.set_xlabel("Number of iteratons")
ax.set_ylabel(r"$J(\theta)$")
plt.tight_layout()
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Podemos observar que el valor de $J(\theta)$ decrece hasta converger a un mínimo. Analicemos el comportamiento del algoritmo para valores de $\alpha$ mayores. Para este ejemplo consideremos $\alpha = 0.21$ usando el mismo punto de partitida para $\theta$.

In [5]:
theta = np.array([[1], [1]])
tol = 0.01
M = 1000
alpha = 0.21

theta_rec, J_rec = steepestDescent(A, b, theta, alpha, tol, M)
data = np.hstack((theta_rec, J_rec))
pd.DataFrame(data, columns=["theta0", "theta1", "J(theta)"])

Maximum number of iterations reached

            theta0    theta1      J(theta)
0     1.000000e+00  1.000000  5.500000e+00
1    -8.900000e-01  0.580000  5.598700e+00
2     1.189000e+00  0.248200  6.158607e+00
3    -1.097900e+00 -0.013922  7.110997e+00
4     1.417690e+00 -0.220998  8.434956e+00
...            ...       ...           ...
996   1.518298e+41 -1.000000  1.152614e+83
997  -1.670127e+41 -1.000000  1.394663e+83
998   1.837140e+41 -1.000000  1.687542e+83
999  -2.020854e+41 -1.000000  2.041926e+83
1000  2.222940e+41 -1.000000  2.470730e+83

[1001 rows x 3 columns]

In [6]:
fig = plt.figure(figsize=(8, 4))
ax = fig.add_subplot(1,1,1)
ax.plot(J_rec, '.')
ax.set_xlabel("Number of iteratons")
ax.set_ylabel(r"$J(\theta)$")
plt.tight_layout()
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Podemos observar que para $\alpha \geq 0.21$ el algoritmo diverge. De este modo debemos buscar un valor para $\alpha$ que permita alcanzar el mínimo en la menor cantidad de iteraciones. Podemos entonces probar con $\alpha = 0.05$.

In [7]:
theta = np.array([[1], [1]])
tol = 0.01
M = 1000
alpha = 0.17

theta_rec, J_rec = steepestDescent(A, b, theta, alpha, tol, M)
data = np.hstack((theta_rec, J_rec))
pd.DataFrame(data, columns=["theta0", "theta1", "J(theta)"])

The procedure was successful.

      theta0    theta1  J(theta)
0   1.000000  1.000000  5.500000
1  -0.530000  0.660000  2.812300
2   0.541000  0.377800  1.371571
3  -0.208700  0.143574  0.580359
4   0.316090 -0.050834  0.133933
5  -0.051263 -0.212192 -0.125277
6   0.205884 -0.346119 -0.280163
7   0.025881 -0.457279 -0.375259
8   0.151883 -0.549542 -0.435084
9   0.063682 -0.626119 -0.473512
10  0.125423 -0.689679 -0.498619
11  0.082204 -0.742434 -0.515246
12  0.112457 -0.786220 -0.526373
13  0.091280 -0.822563 -0.533878
14  0.106104 -0.852727 -0.538969
15  0.095727 -0.877763 -0.542438
16  0.102991 -0.898544 -0.544809
17  0.097906 -0.915791 -0.546433
18  0.101466 -0.930107 -0.547547
19  0.098974 -0.941989 -0.548312
20  0.100718 -0.951850 -0.548838
21  0.099497 -0.960036 -0.549200
22  0.100352 -0.966830 -0.549449
23  0.099754 -0.972469 -0.549621
24  0.100172 -0.977149 -0.549739
25  0.099879 -0.981034 -0.549820
26  0.100084 -0.984258 -0.549876
27  0.099941 -0.986934 -0.549915
28  0.100041 -0.989155 -0.549941
29  0.099971 -0.990999 -0.549959

In [8]:
fig = plt.figure(figsize=(8, 4))
ax = fig.add_subplot(1,1,1)
ax.plot(J_rec, '.')
ax.set_xlabel("Number of iteratons")
ax.set_ylabel(r"$J(\theta)$")
plt.tight_layout()
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

De este modo obtenemos una aproximaxión a un punto de mínima con 29 iteraciones. La siguente figura demuestra el camino que recorre el algoritmo para alcanzar dicho punto. Esta visualización en Jupyter Lab requiere la instalación de [ipympl](https://github.com/matplotlib/ipympl)

In [9]:
# Cost function
def cost(theta0, theta1):
    return 5*theta0**2 + 0.5*theta1**2 - theta0 + theta1

theta0 = np.linspace(-1, 1, 100)
theta1 = np.linspace(-3, 1, 100)
[T0, T1] = np.meshgrid(theta0, theta1)

J = cost(T0, T1)

fig = plt.figure(figsize=(7, 7))
ax = fig.add_subplot(1,1,1, projection="3d")

ax.plot_surface(T0, T1, J, cmap ="jet", alpha=0.5)
ax.contour(T0, T1, J, zdir='z', cmap ="jet", offset = -5)

ax.plot(theta_rec[:, 0], theta_rec[:, 1], J_rec[:, 0], "r")
ax.plot(theta_rec[:, 0], theta_rec[:, 1], -5, "r")

ax.set_zlim3d(-5, 10)
ax.set_xlabel(r"$\theta_0$")
ax.set_ylabel(r"$\theta_1$")
ax.set_zlabel(r"$J(\theta_0, \theta_1)$")
plt.tight_layout()
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …